from passes.optimization.framework.base import Pass, PassContext
from passes.optimization.framework.phases import (
    PreSsaPass,
    PreFixedpointPass,
    FixedpointPass,
    PostFixedpointPass,
    PostDestructionPass,
    PostDestructionFixedpointPass,
    ProgramPass,
)
from passes.optimization.framework.driver import PhaseDriver
from passes.optimization.framework.window import WindowPass
from passes.optimization.framework.defuse import DefUsePass, DefUseEnv, Rewrite
from passes.optimization.framework.operand_rewrite import OperandRewritePass
from passes.optimization.framework.sink import SinkPass
from passes.optimization.framework.patterns import (
    MatchResult,
    Pattern,
    match,
    m_Any,
    m_Constant,
    m_Var,
    m_Specific,
    m_Binary,
    m_Unary,
    m_Copy,
    m_Cast,
    m_JumpIfTrue,
    m_JumpIfFalse,
    m_Store,
    m_Load,
    m_OneOf,
    m_Commutative,
)

__all__ = [
    "Pass",
    "PassContext",
    "PreSsaPass",
    "PreFixedpointPass",
    "FixedpointPass",
    "PostFixedpointPass",
    "PostDestructionPass",
    "PostDestructionFixedpointPass",
    "ProgramPass",
    "PhaseDriver",
    "WindowPass",
    "DefUsePass",
    "DefUseEnv",
    "Rewrite",
    "MatchResult",
    "Pattern",
    "match",
    "m_Any",
    "m_Constant",
    "m_Var",
    "m_Specific",
    "m_Binary",
    "m_Unary",
    "m_Copy",
    "m_Cast",
    "m_JumpIfTrue",
    "m_JumpIfFalse",
    "m_Store",
    "m_Load",
    "m_OneOf",
    "m_Commutative",
    "OperandRewritePass",
    "SinkPass",
]
